export function executeEvent(ele, event, funct) {
  ele.addEventListener(event, () => {
    funct();
  });
}
export function animateLike(like) {
  // console.log(like.style.fill);
  if (like.style.fill === "white") {
    like.style.fill = "#ff4d6c";
    addTofav();
  } else {
    like.style.fill = "white";
    removeFromFav();
  }
}
export const getname = (Name) => {
  const parts = Name.split("/");
  const breed = parts[parts.indexOf("breeds") + 1];
  return breed;
};
export let options = [
  "beagle",
  "hound-plott",
  "bulldog-boston",
  "hound-english",
  "spaniel-welsh",
  "redbone",
  "brabancon",
  "coonhound",
  "hound-walker",
  "bouvier",
  "corgi-cardigan",
  "spaniel-blenheim",
  "poodle-miniature",
  "groenendael",
  "spaniel-japanese",
  "saluki",
  "tervuren",
  "spaniel-cocker",
  "terrier-yorkshire",
  "kuvasz",
  "finnish-lapphund",
  "sheepdog-shetland",
  "mastiff-english",
  "dachshund",
  "bluetick",
  "labrador",
  "retriever-golden",
  "terrier-westhighland",
  "retriever-flatcoated",
  "setter-gordon",
  "weimaraner",
  "boxer",
  "sheepdog-indian",
  "newfoundland",
  "poodle-medium",
  "dalmatian",
  "spaniel-irish",
  "vizsla",
  "segugio-italian",
  "otterhound",
  "terrier-fox",
  "hound-blood",
  "schipperke",
  "spaniel-brittany",
  "eskimo",
  "havanese",
  "appenzeller",
  "terrier-silky",
  "spaniel-sussex",
  "borzoi",
  "waterdog-spanish",
  "mountain-swiss",
  "elkhound-norwegian",
  "kombai",
  "labradoodle",
  "entlebucher",
  "terrier-dandie",
  "wolfhound-irish",
  "greyhound-indian",
  "terrier-american",
  "terrier-tibetan",
  "ovcharka-caucasian",
  "mastiff-bull",
  "setter-irish",
  "springer-english",
  "terrier-irish",
  "hound-basset",
  "buhund-norwegian",
  "spitz-japanese",
  "bulldog-french",
  "terrier-lakeland",
  "deerhound-scottish",
  "dane-great",
  "pug",
  "pitbull",
  "lhasa",
  "leonberg",
  "pomeranian",
  "cotondetulear",
  "kelpie",
  "terrier-scottish",
  "sheepdog-english",
  "affenpinscher",
  "setter-english",
  "gaddi-indian",
  "terrier-toy",
  "terrier-wheaten",
  "puggle",
  "pinscher-miniature",
  "terrier-norwich",
  "cockapoo",
  "bakharwal-indian",
  "papillon",
  "terrier-kerryblue",
  "terrier-bedlington",
  "bulldog-english",
  "rajapalayam-indian",
  "pembroke",
  "poodle-standard",
  "pariah-indian",
  "none",
];
